### PR TITLE
Introduce an enum for the boardstate

### LINKED ISSUE #4: Improve "slow" code
```
if (board[y][x] == 'X')
	printf("\033[34m\033[1m %c ", board[y][x]);
```
Why using printf with variable replacement while the replacement is always a fixed value. (in this Example 'X'.
This will may speed up your programm.On a 3GHz processor, in a CLI this may doen't matter, but hey, it's possible. ;)

### LINKED ISSUE #5: Using enums instead chars for board "status".
Instead of 'X' 'O' and ' ' you can create an enum with states like 'player_A', 'player_B' or 'free'. You can even introduce 'blocked' state.
This makes code more readable and splits 'data' better from 'view'. So you can introduce some symbol or color picking at the beginning of the game. Or you can change from CLI to a real GUI or 3d animation without changing your core game engine. ;)

### PR DESCRIPTION
**Pull request by jensboe**
I hope this works.
Not compiled and not tested.
Normally I don't write code in my browser.

This will fix #5 and will fix #4.

You need to test this. ;)

### CODE REVIEW

**Comment by xemeds** [comment]
Thank you for implementing enumerators. I didn't know what they were, had to look up on them. And I also fixed a few things before merging.

**Comment by jensboe** [comment]
I know that Python don't have them. But they are nice and improve readability. So I introduce them to you.
I think best code ist code which don't need comments (or only comments for describing complex functions).

The default case is not needed but it's more robust to let it inside. and output some "not implemented" error message like an exception raise in Python. May stderr will be nice for that. But I don't write C desktop code, so i don't know what's best case for that.
My embedded code will turn the device into a brick if that happens and write much as it has into a non volatile memory.

**Comment by jensboe** [comment]
> And I also fixed a few things before merging.

I make less syntax errors than expected. 😄

**Comment by xemeds** [comment]
> My embedded code will turn the device into a brick if that happens and write much as it has into a non volatile memory.

I would love to see it whenever that happens. :smile:

**Comment by jensboe** [comment]
> I would love to see it whenever that happens. 😄

Our costumer don't like it. My boss don't like it. I don't like it if it happens at costumers.

You may can test it, if you want add a simple `board[0][0] = 42;`, depending on your compiler settings it may warn you or throw an error, but hopefully, it ~~works~~ breaks.

**Comment by jensboe** [comment]
Broken:
Entering a1 is not possible:
image
Non direct fields wont fix:
image

but a2 repairs state of a1:
image

**Comment by xemeds** [comment]
Intentionally breaking the program. :smile:
I now understand why you wrote PANIC!!! in the default switch statement.

**Pull request merged**
